---
title: The Domestic Tranquility Act of 2021
author: Richard Careaga
date: '2020-06-12'
slug: the-domestic-tranquility-act-of-2021
categories:
  - Politics
tags:
  - BLM
---

# PRESIDENT BIDEN SIGNS THE DOMESTIC TRANQUILITY ACT

(March 26, 2021, Washington, DC, Global Wire) The Domestic Tranquility Act became law in a White House signing ceremony this week after weeks of tumultuous debate in Congress and often violent protects by opponents.

“This law will not end racism,” said President Biden, “but it will put an end to the use of police to prolong it.”

He praised Vice President Kamala Harris for shepherding the bill through Congress and the Senate Republicans who defied their leadership to support the legislation. “The leadership that she showed in this great achievement is exactly the reason I chose her to be my running mate,” the President said. “She forged a bipartisan alliance in partnership with Senator Mitt Romney. Kamala, Mitt, you get the first pens.”

The DTA represents a massive restructuring of policing in America. It creates a National Policy Academy, modeled on the military service academies, pays the salaries of qualifying municipal police officers and establishes strict new standards for police use of force.

Senate Minority Leader John Thune (R-ND) denounced the legislation as the first step to complete federalization of local government. “Next,” he said in a news conference following the White House ceremony, “the jackboots of the Democrat administration will be on the necks of law-abiding citizens everywhere.” He added that “the majority of elected officials in my home state of Nouth Dakota completely agree with me, including 100% of Negros.” State Treasurer Josh Haeder, the only African-American official elected to statewide office in North Dakota, could not be reached for comment.

A protest outside the White House suddenly dispersed after after an unidentified man fired a shot at a Marine standing guard at the portico entrance to the building. He was shot and killed by Secret Service Snipers before he could fire again. The gunman’s round apparently fell short. The gunman has not yet been identified. He was one of a group of approximately 1,000 demonstrators dressed in camouflage, carrying automatic rifles and Confederate flags. Police recovered approximately two dozen abandoned firearms. Press Secretary Yamiche Alcindor stated that the President was not aware of the incident at the time of the shooting and that the Secret Service does not comment on investigations in progress.

The bill amends the Civil Rights Act of 1964 to make many police practices a criminal violation of federal law. One provision specifically prohibits any form of asphyxiation restraint, such as that involved in the murder of George Floyd on Memorial Day, May 20, 2020. Graduates of the new National Police Academy will be subject to procedures to be enacted into law later to be similar to the Uniform Code of Military Justice.

Local jurisdictions will be eligible to have the salary and benefits of all peace officers paid by the federal government. A phase-out for currently employed police officers will take place over a 20-year period. Local police departments will agree to hire only graduates of the National Police Academy beginning in 2030. A two-year program for experienced police officers will allow existing officers to qualify. That program and a four-year program for “rookie” police officers will be tuition/room and board paid free. Graduates will be required to server for a minimum of five years. Drop-outs will serve three years in the armed services. Local communities will be able to nominate candidates for admissions, proportional ethnically to their populations. Candidates will receive rigorous background checks.

“Equal justice for all means the same justice for all, not separate justice,” said Vice President Harris. This act will not get us all the way there immediately, but it will get us there.”